### ISSUE TITLE
SILO runs do not terminate after they have run through

### ISSUE THREAD

**Issue by dziemke** [msmobility/silo#295] opened 2020-04-25 09:31 UTC
Even after
"2020-04-25 11:19:30,633  INFO SiloUtil:1089 Runtime: 0 hours and 27 minutes."
the runs never terminate technically.
I speculate that this is related to some multithreaded component of the model where the threads have not been terminated properly.
The lack of the proper termination of the run may not be the biggest issue in its won right, but (if above speculation about threads is correct) could be a hint for (undiscovered) issues with the multithreaded components of the code.

**Comment by nkuehnel** [comment] 2020-04-26 16:01
This has been there for quite some time and is indeed caused by threads not closing entirely. However, there should not be any further issues that impact results of the model (we tested results against single threaded runs). 
We haven't had time to fix this annoying issue though..

**Comment by nkuehnel** [comment] 2020-04-27 00:55
The utility calculation that starts threads to await routing requests in the housing evaluation did not end the threads after the simulation. Since those threads are somehow permanent worker threads I would for now set them as daemon threads to allow proper shutdown of the vm (unless we find arguments against this)

**Closed** 2020-04-27 01:24 UTC
Labels: bug :beetle:, question :question:
